// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"bysos/app/info/internal/biz"
	"bysos/app/info/internal/conf"
	"bysos/app/info/internal/data"
	"bysos/app/info/internal/server"
	"bysos/app/info/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, registry *conf.Registry, logger log.Logger) (*kratos.App, func(), error) {
	discovery := server.NewDiscovery(registry)
	dataData, cleanup, err := data.NewData(confData, registry, discovery, logger)
	if err != nil {
		return nil, nil, err
	}
	infoRepo := data.NewInfoRepo(dataData, logger)
	infoUsecase := biz.NewInfoUsecase(infoRepo, logger)
	infoService := service.NewInfoService(infoUsecase)
	grpcServer := server.NewGRPCServer(confServer, infoService, logger)
	httpServer := server.NewHTTPServer(confServer, infoService, logger)
	registrar := server.NewRegistrar(registry, logger)
	app := newApp(logger, grpcServer, httpServer, registrar)
	return app, func() {
		cleanup()
	}, nil
}
